# Generated by Django 5.1.3 on 2024-11-15 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_remove_simulation_description_remove_simulation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='simulation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
